# Generated by Django 5.1.2 on 2024-11-05 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_alter_content_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='file',
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('file', 'File'), ('image', 'Image'), ('text', 'Text')], max_length=50),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='assignments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.module')),
            ],
        ),
    ]
