# Generated by Django 5.1.2 on 2024-11-11 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_content_file_alter_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_from_courses', to='courses.module'),
        ),
    ]
