# Generated by Django 5.1.2 on 2024-10-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
